name: CI
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.3.2
          arch: win64_msvc2019_64
          archives: qtbase qtsvg
          extra: --external 7z
      - name: Update environment variables
        run: |
          Write-Output "${{ runner.workspace }}\rl-3rdparty-install\bin" | Out-File -FilePath $Env:GITHUB_PATH -Encoding utf8 -Append
      - name: Configure CMake
        run: >
          cmake
          -G"Ninja Multi-Config"
          -DCPACK_INSTALL_CMAKE_PROJECTS=""
          -DCMAKE_INSTALL_PREFIX="${{ runner.workspace }}/rl-3rdparty-install"
          -DCPACK_INSTALLED_DIRECTORIES="${{ runner.workspace }}/rl-3rdparty-install;."
          -DCPACK_MONOLITHIC_INSTALL=ON
          -S"${{ github.workspace }}"
          -B"${{ github.workspace }}/build"
      - name: Build Debug
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config Debug
      - name: Build Release
        working-directory: ${{ github.workspace }}/build
        run: cmake --build . --config Release
      - name: Create archive
        working-directory: ${{ github.workspace }}/build
        run: cpack -G 7Z
      - name: Upload archive
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ github.workspace }}/build/rl-3rdparty-*.7z
          file_glob: true
          overwrite: true
          prerelease: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest
